/*
 * generated by Xtext 2.32.0
 */
package com.coffee.ui;

import com.coffee.hlvl.ui.internal.HlvlActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class HlvlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(HlvlActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		HlvlActivator activator = HlvlActivator.getInstance();
		return activator != null ? activator.getInjector(HlvlActivator.COM_COFFEE_HLVL) : null;
	}

}
