/**
 * generated by Xtext 2.12.0
 */
package com.coffee.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class HlvlIdeModule extends AbstractHlvlIdeModule {
}
